name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup .NET for building
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.300

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test -c Release

    - name: Formatting
      run: |
        dotnet tool install -g dotnet-format
        dotnet format  --verify-no-changes
